apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  secretObjects:                              
    - secretName: jwt-signing                  
      type: Opaque
      data:
      - objectName: jwt-signing              
        key: jwt-signing-key                  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"              
    keyvaultName: "sit722hd-kv"      
    objects: |
      array:
        - |
          objectName: jwt-signing
          objectType: secret                 
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
